name: Build

on:
  pull_request:
  push:
    branches:
    - main-Stelzi79

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: continuous-integration/github
    steps:
    - name: checkout
      uses: actions/checkout@a14471d83
    - name: build
      run: "./test.sh"
