name: Test Function of Action

on:
  push:
    tags: 
      - '*'
    branches:
      - main-Stelzi79

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: run minver
      id: version
      uses: Stelzi79/action-minver@main-Stelzi79
      with:
        # Optional. Specifies which part of the version to auto-increment.
        auto-increment: patch
        # Optional. Sets custom build metadata for your semantic version.
        build-metadata: ${{ github.sha }}
        # Optional. Specifies the default pre-release phase.
        default-pre-release-phase: preview
        # Optional. Specifies the minimum version to use when no tags exist.
        minimum-major-minor: 2.0.0
        # Optional. Specifies the prefix of the tags
        tag-prefix: v
        # Optional. Specifies the log level.
        verbosity: trace
    - name: output
      run: |
        echo Version ${{ steps.version.outputs.version }}
